apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: dg0402-lifesub-ns
type: Opaque
stringData:
  JWT_SECRET_KEY: "0k5WTp6/dtoWNcHtXShV6SAK7B7qg+1uCSSPEoyyzvqlVA3PY68PCXmbRNgIUigJ9oUc/9cD6xFeVbW61ODpiQ=="
